version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nan1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j5hcubvh0lmo"
s3_prefix = "nan1"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

