AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: The resume challenge, create lambda and api.
Resources:
  hitsGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
  ncounter:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./ncounter/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ntable
      Environment:
        Variables:
          TABLE_NAME: "ntable"
      Description: This lambda updates count item on Dyndb.
      MemorySize: 128
      Timeout: 3
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /num
            Method: get
            RestApiId:
              Ref: hitsGateway
